version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
    environment:
      MONGO_INITDB_DATABASE: esports-platform
  
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'